// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hojcrgvdvvrfdnyccgej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvamNyZ3ZkdnZyZmRueWNjZ2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1OTI5NzEsImV4cCI6MjA1NzE2ODk3MX0.YuLuUgc6twqbcu9dhBs8Zvm17ThYHPVxhv_QfJLdkRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);